# Generated by Django 4.1.1 on 2022-09-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to='categories/baner/'),
        ),
    ]
