# Generated by Django 4.1.1 on 2022-09-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_category_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='titel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
