# Generated by Django 4.1.1 on 2022-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_product_images_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(upload_to='products/images/<django.db.models.query_utils.DeferredAttribute object at 0x000002060AA8DD20>/'),
        ),
    ]
