# Generated by Django 4.1.1 on 2022-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_product_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(upload_to='products/images/%y/%m/%d/'),
        ),
    ]
