# Generated by Django 4.1.1 on 2022-09-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_product_images_slug_alter_product_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='baner',
        ),
    ]
