# Generated by Django 4.1.1 on 2022-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_category_slug_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
