# Generated by Django 4.1.1 on 2022-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_product_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stockag',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
